name: CI

on:
  push:
    branches: [ main, develop, review ]
  pull_request:
    branches: [ main, develop ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [18.x, 20.x]
        
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Run linting
      run: npm run lint
      
    - name: Run tests
      run: npm run test:coverage
      
    - name: Upload coverage to Codecov
      if: matrix.node-version == '20.x'
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage/lcov.info
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: false

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: test
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Use Node.js 20.x
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build package
      run: npm run build
      
    - name: Check build artifacts
      run: |
        echo "Checking dist directory contents:"
        ls -la dist/
        echo "Checking if all required files are present:"
        test -f dist/index.js || exit 1
        test -d dist/nodes || exit 1
        test -d dist/credentials || exit 1
        test -d dist/icons || exit 1
        echo "Build artifacts check passed!"
        
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build-artifacts-node-20
        path: |
          dist/
          package.json
          README.md
          LICENSE
        retention-days: 7

  lint-examples:
    name: Validate Examples
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Validate JSON examples
      run: |
        echo "Validating example workflow JSON files..."
        for file in examples/*.json; do
          echo "Validating $file"
          if ! jq empty "$file" 2>/dev/null; then
            echo "ERROR: $file is not valid JSON"
            exit 1
          fi
          echo "✓ $file is valid JSON"
        done
        echo "All example files are valid JSON!"

  security:
    name: Security Audit
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Use Node.js 20.x
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Run security audit
      run: npm audit --audit-level=high
      continue-on-error: true
      
    - name: Run dependency check
      run: |
        echo "Checking for known vulnerabilities in dependencies..."
        npx better-npm-audit audit --production
      continue-on-error: true